import { access, mkdir, readFile, stat, writeFile } from "node:fs/promises";
import path from "node:path";

export const MARKER_START = "# --- BEGIN AGENTIC REPO EXCLUDES ---";
export const MARKER_END = "# --- END AGENTIC REPO EXCLUDES ---";

export const DEFAULT_EXCLUDE_PATTERNS = [
  ".agents/",
  "scaffold.yaml",
  "scaffold.lock",
  "AGENTS.md",
  "THIRD_PARTY_NOTICES.md",
  "docs/raw/",
  "docs/wiki/",
  "docs/adr/",
  "docs/product/",
  "docs/specs/",
  "docs/templates/",
  "CLAUDE.md",
  "GEMINI.md",
  ".github/copilot-instructions.md",
  ".github/agents/",
  ".cursorrules",
  ".opencode/",
  ".kiro/",
];

export async function resolveGitExcludePath(cwd) {
  const gitPath = path.join(cwd, ".git");
  try {
    const gitStat = await stat(gitPath);
    if (gitStat.isDirectory()) {
      return path.join(gitPath, "info", "exclude");
    }
    if (gitStat.isFile()) {
      const content = await readFile(gitPath, "utf8");
      const match = content.match(/^gitdir:\s*(.+)$/m);
      if (match) {
        const resolvedGitDir = path.resolve(cwd, match[1].trim());
        return path.join(resolvedGitDir, "info", "exclude");
      }
    }
  } catch {
    return null;
  }
  return null;
}

function stripManagedBlock(content) {
  const startIndex = content.indexOf(MARKER_START);
  const endIndex = content.indexOf(MARKER_END);
  if (startIndex === -1 || endIndex === -1 || endIndex < startIndex) {
    return content.trim();
  }
  const before = content.slice(0, startIndex).trimEnd();
  const after = content.slice(endIndex + MARKER_END.length).trimStart();
  const combined = [before, after].filter(Boolean).join("\n\n");
  return combined.trim();
}

export async function applyGitExclude(cwd, customPatterns = null) {
  const excludePath = await resolveGitExcludePath(cwd);
  if (!excludePath) {
    return { ok: false, reason: "no-git", path: null };
  }

  let existing = "";
  try {
    existing = await readFile(excludePath, "utf8");
  } catch {
    existing = "";
  }

  const cleaned = stripManagedBlock(existing);
  const patterns = customPatterns && customPatterns.length > 0 ? customPatterns : DEFAULT_EXCLUDE_PATTERNS;

  const blockLines = [
    MARKER_START,
    "# Generated by agentic-repo-kit. Managed automatically.",
    ...patterns,
    MARKER_END,
  ];

  const newContent = cleaned.length > 0
    ? `${cleaned}\n\n${blockLines.join("\n")}\n`
    : `${blockLines.join("\n")}\n`;

  await mkdir(path.dirname(excludePath), { recursive: true });
  await writeFile(excludePath, newContent, "utf8");

  return { ok: true, path: excludePath, patterns };
}

export async function removeGitExclude(cwd) {
  const excludePath = await resolveGitExcludePath(cwd);
  if (!excludePath) {
    return { ok: false, reason: "no-git", path: null };
  }

  let existing = "";
  try {
    existing = await readFile(excludePath, "utf8");
  } catch {
    return { ok: true, path: excludePath, removed: false };
  }

  const cleaned = stripManagedBlock(existing);
  const newContent = cleaned.length > 0 ? `${cleaned}\n` : "";

  await writeFile(excludePath, newContent, "utf8");
  return { ok: true, path: excludePath, removed: true };
}

export async function inspectGitExclude(cwd) {
  const excludePath = await resolveGitExcludePath(cwd);
  if (!excludePath) {
    return { ok: false, reason: "no-git", active: false, patterns: [] };
  }

  try {
    const content = await readFile(excludePath, "utf8");
    const startIndex = content.indexOf(MARKER_START);
    const endIndex = content.indexOf(MARKER_END);
    if (startIndex !== -1 && endIndex !== -1 && endIndex > startIndex) {
      const block = content.slice(startIndex + MARKER_START.length, endIndex);
      const patterns = block
        .split("\n")
        .map((line) => line.trim())
        .filter((line) => line && !line.startsWith("#"));
      return { ok: true, path: excludePath, active: true, patterns };
    }
    return { ok: true, path: excludePath, active: false, patterns: [] };
  } catch {
    return { ok: true, path: excludePath, active: false, patterns: [] };
  }
}
